language: node_js
matrix:
  include:
    - node_js: "8"
      env: BROWSER_TEST=false
    - node_js: "stable"
      env: BROWSER_TEST=false
    - node_js: "stable"
      env: BROWSER_TEST=true
sudo: false
script:
  - .travis/test.sh
cache:
  directories:
    - node_modules
