language: node_js
matrix:
  include:
    - node_js: "0.12"
      env: BROWSER_TEST=false
    - node_js: "4.2"
      env: BROWSER_TEST=false
    - node_js: "stable"
      env: BROWSER_TEST=false
    - node_js: "stable"
      env: BROWSER_TEST=true
sudo: false
before_install:
  - .travis/setup.sh
script:
  - .travis/test.sh
cache:
  directories:
    - node_modules
