version: 2.1
executors:
  node14:
    docker:
      - image: cimg/node:14.21.0-browsers
jobs:
  test_node:
    executor: node10
    steps:
      - checkout
      - restore_cache:
          key: jsforce-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: jsforce-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Lint and Type Check
          command: |
            npm run lint
            npm run build:types
            npm run typecheck
      - run:
          name: Test
          command: |
            npm run test:node
  test_browser:
    executor: node10
    steps:
      - checkout
      - restore_cache:
          key: jsforce-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: jsforce-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
      - run:
          name: Test
          command: |
            npm run test:browser
workflows:
  version: 2
  test:
    jobs:
      - test_node
      - test_browser
